### ISSUE TITLE
add dropzone.js to allow for image file uploaded in order to be analyzed

### ISSUE THREAD

**Issue by QuantumPhilosophy** [QuantumPhilosophy/anonymous-pumpkin#13]
### User Stories
**Landing Page:** User sees inputs to provide an image URL and is presented with information based on the image subjects

### Tasks
- [ ] Import [dropzone.js](https://www.dropzonejs.com/) into the project
- [ ] Add a section for dropzone UI in the HTML
- [ ] Direct file uploads to Firebase Storage

## Issue Links
**Depends On:** #4 start a Firebase project and initialize in Javascript - Complete
