### ISSUE TITLE
informational splash modal only appears once per user on initial page load

### ISSUE THREAD

**Issue by QuantumPhilosophy** [QuantumPhilosophy/anonymous-pumpkin#18]
### Tasks
- [ ] Hook the informational splash modal into a `splashModalSeen` boolean stored per user and set `= false`
- [ ] When modal is closed update `splashModalSeen = true`
- [ ] Informational splash modal only shows when `splashModalSeen = false`

### Issue Links
**Depends On:** #15 showing only images searched by user
