### ISSUE TITLE
Put fresh labels on firebase and deal with them

### ISSUE THREAD

**Issue by Glacian22** [QuantumPhilosophy/anonymous-pumpkin#39]
## tasks
- [x] make newLabels var on firebase
- [x] when Cloud Vision returns labels, update newLabels on FB
- [ ] when newLabels changed, offer buttons to user
