### ISSUE TITLE
start a Firebase project and initialize in Javascript

### ISSUE THREAD

**Issue by QuantumPhilosophy** [QuantumPhilosophy/anonymous-pumpkin#4]
### User Story
**Backend:** Images searched for will be in a community pool. Each user that loads the app will see the images other users have searched for previously

### Tasks
- [x] Start a Firebase project in the Firebase console
- [x] Add the Javascript `<script>` import tag to the HTML
- [x] Add the Firebase initialization code to `app.js`

**Comment by QuantumPhilosophy** [comment]
#2 covers this issue.
